# Site settings
title: Ragu
name: Ragu
email: ragu@misterblue.com
description: > # this means to ignore newlines until "baseurl:"
    Ragu OpenSimulator space server

baseurl: "/ragu" # the subpath of your site, e.g. /blog/
url: "http://misterblue.github.io" # the base hostname & protocol for your site

# twitter_username: misterblue
github_username:  misterblue

# Set this to your UA-# value, or '' to disable the block completely
# gaaccount: 'UA-63061357-1'
gaaccount: ''

permalink: /:year/:year-:month-:day-:title

highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
encoding: utf-8

exclude: ['README.md', 'LICENSE']
encoding: utf-8
